name: Test Dispatch

on:
  workflow_dispatch:
    inputs:
      name:
        description: "A test input"
        required: false
        default: "world"

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello ${{ github.event.inputs.name }}"
